name: JAlert Cron Job

on:
  # Triggers the workflow every 10 minutes
  schedule:
    - cron: "*/10 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
        run: npm i && npm start
